import type { Metadata } from "next";
import "./globals.css";
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        {/* Header */}
        <Header />

        {/* Conteúdo principal com Sidebar e Main */}
        <div className="flex flex-1">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Content */}
          <main className="flex-1 bg-gray-100 p-4">{children}</main>
        </div>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}